"""add pipeline rbac health and linked service models

Revision ID: 0f849556d1b9
Revises: 18585587f4e1
Create Date: 2026-03-01 14:37:14.169558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f849556d1b9'
down_revision: Union[str, None] = '18585587f4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('granted_by', sa.String(length=255), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_type', 'resource_id', name='uq_membership_user_resource')
    )
    op.create_index('ix_membership_resource', 'memberships', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_membership_user_id', 'memberships', ['user_id'], unique=False)
    op.create_table('health_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('check_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('action_taken', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_events_site_id'), 'health_events', ['site_id'], unique=False)
    op.create_table('linked_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('container_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('connection_env', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delete_on_site_removal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linked_services_site_id'), 'linked_services', ['site_id'], unique=False)
    op.create_index(op.f('ix_linked_services_tenant_id'), 'linked_services', ['tenant_id'], unique=False)
    op.create_table('notification_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_configs_site_id'), 'notification_configs', ['site_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('git_provider', sa.String(length=32), nullable=True),
    sa.Column('git_ref', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('commit_author', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('build_driver', sa.String(length=64), nullable=True),
    sa.Column('image_ref', sa.String(length=512), nullable=True),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_site_id'), 'pipeline_runs', ['site_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_tenant_id'), 'pipeline_runs', ['tenant_id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_pipeline_run_id'), 'pipeline_stages', ['pipeline_run_id'], unique=False)
    op.add_column('sites', sa.Column('git_provider', sa.String(length=32), nullable=True))
    op.add_column('sites', sa.Column('git_provider_url', sa.String(length=1024), nullable=True))
    op.add_column('sites', sa.Column('git_branch', sa.String(length=255), nullable=True))
    op.add_column('sites', sa.Column('auto_deploy', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('sites', sa.Column('webhook_secret', sa.String(length=255), nullable=True))
    op.add_column('sites', sa.Column('last_deployed_sha', sa.String(length=64), nullable=True))
    op.add_column('sites', sa.Column('git_token_username', sa.String(length=255), nullable=True))
    op.add_column('sites', sa.Column('git_token', sa.String(length=512), nullable=True))
    op.add_column('sites', sa.Column('build_driver', sa.String(length=64), nullable=True))
    op.add_column('sites', sa.Column('scan_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('sites', sa.Column('scan_fail_on', sa.String(length=16), nullable=True))
    op.add_column('sites', sa.Column('health_failure_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('sites', sa.Column('health_status', sa.String(length=16), nullable=True))
    op.add_column('sites', sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('last_healthy_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('active_container_id', sa.String(length=255), nullable=True))
    op.add_column('sites', sa.Column('pending_container_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'pending_container_id')
    op.drop_column('sites', 'active_container_id')
    op.drop_column('sites', 'last_healthy_at')
    op.drop_column('sites', 'last_health_check')
    op.drop_column('sites', 'health_status')
    op.drop_column('sites', 'health_failure_count')
    op.drop_column('sites', 'scan_fail_on')
    op.drop_column('sites', 'scan_enabled')
    op.drop_column('sites', 'build_driver')
    op.drop_column('sites', 'git_token')
    op.drop_column('sites', 'git_token_username')
    op.drop_column('sites', 'last_deployed_sha')
    op.drop_column('sites', 'webhook_secret')
    op.drop_column('sites', 'auto_deploy')
    op.drop_column('sites', 'git_branch')
    op.drop_column('sites', 'git_provider_url')
    op.drop_column('sites', 'git_provider')
    op.drop_index(op.f('ix_pipeline_stages_pipeline_run_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_pipeline_runs_tenant_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_site_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_notification_configs_site_id'), table_name='notification_configs')
    op.drop_table('notification_configs')
    op.drop_index(op.f('ix_linked_services_tenant_id'), table_name='linked_services')
    op.drop_index(op.f('ix_linked_services_site_id'), table_name='linked_services')
    op.drop_table('linked_services')
    op.drop_index(op.f('ix_health_events_site_id'), table_name='health_events')
    op.drop_table('health_events')
    op.drop_index('ix_membership_user_id', table_name='memberships')
    op.drop_index('ix_membership_resource', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
