"""initial_models

Revision ID: 18585587f4e1
Revises: 
Create Date: 2026-02-19 01:58:45.910530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18585587f4e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.Enum('free', 'starter', 'pro', 'enterprise', name='plan_type'), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('adhara_api_url', sa.String(length=512), nullable=True),
    sa.Column('adhara_api_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=False)
    op.create_index(op.f('ix_workspaces_tenant_id'), 'workspaces', ['tenant_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('git_repo', 'docker_image', 'docker_registry', 'upload', name='source_type'), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('dockerfile_path', sa.String(length=512), nullable=True),
    sa.Column('build_command', sa.String(length=1024), nullable=True),
    sa.Column('container_port', sa.Integer(), nullable=False),
    sa.Column('host_port', sa.Integer(), nullable=True),
    sa.Column('deploy_target', sa.Enum('local', 'cloud_run', 'aws_ecs', 'azure_container', 'kubernetes', name='deploy_target'), nullable=False),
    sa.Column('deploy_region', sa.String(length=64), nullable=True),
    sa.Column('custom_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('runtime_env', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('build_env', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('health_check_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('stopped', 'building', 'deploying', 'running', 'error', name='site_status'), nullable=False),
    sa.Column('current_deployment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_slug'), 'sites', ['slug'], unique=False)
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sites_workspace_id'), 'sites', ['workspace_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('image_tag', sa.String(length=512), nullable=True),
    sa.Column('container_port', sa.Integer(), nullable=True),
    sa.Column('host_port', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'building', 'pushing', 'deploying', 'live', 'failed', 'rolled_back', name='deployment_status'), nullable=False),
    sa.Column('build_logs', sa.Text(), nullable=True),
    sa.Column('deploy_logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deployed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_site_id'), 'deployments', ['site_id'], unique=False)
    op.create_index(op.f('ix_deployments_tenant_id'), 'deployments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_tenant_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_site_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_sites_workspace_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_slug'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_workspaces_tenant_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
