#!/usr/bin/env bash
set -euo pipefail

# ── Adhara Engine — Production Security Hardening ──────────────────
# This script configures UFW firewall, enables HTTPS via Let's Encrypt,
# and locks down internal service ports.
#
# Prerequisites:
#   - Ubuntu/Debian server with root or sudo access
#   - A domain pointing to this server's IP (for HTTPS)
#   - Adhara Engine running via docker compose
#
# Usage:
#   sudo bash scripts/adhara-secure.sh

# ── Check root ──────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  echo "❌ This script must be run as root (or with sudo)."
  exit 1
fi

# ── Source .env ─────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"
if [ -f "$ENV_FILE" ]; then
  set -a; source "$ENV_FILE"; set +a
fi

ADHARA_HOST="${ADHARA_HOST:-localhost}"
ADHARA_DOMAIN="${ADHARA_DOMAIN:-}"

echo ""
echo "══════════════════════════════════════════════════════════════════"
echo "  Adhara Engine — Production Security Hardening"
echo "══════════════════════════════════════════════════════════════════"
echo ""

# ── Step 1: UFW Firewall ────────────────────────────────────────────
echo "──────────────────────────────────────────────────────────────────"
echo "  Step 1: Configure UFW Firewall"
echo "──────────────────────────────────────────────────────────────────"
echo ""

# Install UFW if not present
if ! command -v ufw &> /dev/null; then
  echo "📦 Installing UFW..."
  apt-get update -qq && apt-get install -y -qq ufw
fi

echo "🔧 Configuring firewall rules..."

# Reset UFW to defaults (non-interactive)
ufw --force reset > /dev/null 2>&1

# Default policies: deny incoming, allow outgoing
ufw default deny incoming > /dev/null 2>&1
ufw default allow outgoing > /dev/null 2>&1

# Allow SSH (critical — don't lock yourself out!)
ufw allow 22/tcp comment "SSH" > /dev/null 2>&1

# Allow HTTP and HTTPS (Traefik)
ufw allow 80/tcp comment "HTTP (Traefik)" > /dev/null 2>&1
ufw allow 443/tcp comment "HTTPS (Traefik)" > /dev/null 2>&1

# Note: Zitadel is routed through Traefik on port 80/443 — no separate port needed

# Enable UFW
ufw --force enable > /dev/null 2>&1

echo "✅ UFW enabled with the following rules:"
echo ""
ufw status numbered
echo ""
echo "  ✅ Allowed: SSH (22), HTTP (80), HTTPS (443)"
echo "  🔒 Blocked: Postgres (5432), Redis (6379), MinIO (9000/9001),"
echo "              Registry (5000), Grafana (3003), Loki (3100),"
echo "              Traefik Dashboard (8080), API direct (8000)"
echo ""

# ── Step 2: HTTPS with Let's Encrypt ───────────────────────────────
echo "──────────────────────────────────────────────────────────────────"
echo "  Step 2: HTTPS with Let's Encrypt"
echo "──────────────────────────────────────────────────────────────────"
echo ""

if [ -z "$ADHARA_DOMAIN" ]; then
  echo "  ⚠️  No ADHARA_DOMAIN set in .env — skipping HTTPS setup."
  echo ""
  echo "  To enable HTTPS later:"
  echo "    1. Point a domain (A record) to this server's IP"
  echo "    2. Add to .env:"
  echo "         ADHARA_DOMAIN=engine.yourdomain.com"
  echo "         ACME_EMAIL=you@yourdomain.com"
  echo "    3. Re-run: sudo bash scripts/adhara-secure.sh"
  echo ""
else
  echo "  🔒 Configuring HTTPS for: ${ADHARA_DOMAIN}"
  echo ""

  ACME_EMAIL="${ACME_EMAIL:-admin@adharaweb.com}"
  PROJECT_DIR="${SCRIPT_DIR}/.."
  DYNAMIC_CFG="${PROJECT_DIR}/traefik/dynamic/services.yml"

  # Enable HTTPS routers in Traefik dynamic config
  # Add HTTPS redirect middleware and secure routers
  cat > "${PROJECT_DIR}/traefik/dynamic/https.yml" <<YAMLEOF
# ============================================================
# Traefik Dynamic Config - HTTPS / Let's Encrypt
# ============================================================
# Auto-generated by adhara-secure.sh

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    # Redirect HTTP → HTTPS
    http-redirect:
      rule: "HostRegexp(\`.+\`)"
      entryPoints: [web]
      middlewares: [redirect-to-https]
      service: noop@internal
      priority: 1000

    # UI on HTTPS
    ui-secure:
      rule: "Host(\`${ADHARA_DOMAIN}\`)"
      entryPoints: [websecure]
      service: ui
      tls:
        certResolver: letsencrypt
      priority: 1

    # API on HTTPS
    api-secure:
      rule: "Host(\`${ADHARA_DOMAIN}\`) && (PathPrefix(\`/api\`) || PathPrefix(\`/docs\`) || PathPrefix(\`/openapi.json\`) || PathPrefix(\`/health\`))"
      entryPoints: [websecure]
      service: api-backend
      tls:
        certResolver: letsencrypt
      priority: 100

    # Docker Registry on HTTPS (registry.DOMAIN → registry:5000)
    registry-secure:
      rule: "Host(\`registry.${ADHARA_DOMAIN}\`)"
      entryPoints: [websecure]
      service: registry
      tls:
        certResolver: letsencrypt
      priority: 100

    # Zitadel OIDC + API on HTTPS (routed through port 443)
    zitadel-web-secure:
      rule: "Host(\`${ADHARA_DOMAIN}\`) && (PathPrefix(\`/oauth\`) || PathPrefix(\`/oidc\`) || PathPrefix(\`/.well-known\`) || PathPrefix(\`/ui/console\`) || PathPrefix(\`/debug\`) || PathPrefix(\`/management/v1\`) || PathPrefix(\`/admin/v1\`) || PathPrefix(\`/auth/v1\`) || PathPrefix(\`/v2\`) || PathPrefix(\`/caos\`) || PathPrefix(\`/zitadel\`))"
      entryPoints: [websecure]
      service: zitadel-api
      tls:
        certResolver: letsencrypt
      priority: 200

    zitadel-login-secure:
      rule: "Host(\`${ADHARA_DOMAIN}\`) && PathPrefix(\`/ui/v2/login\`)"
      entryPoints: [websecure]
      service: zitadel-login
      tls:
        certResolver: letsencrypt
      priority: 300
YAMLEOF

  echo "  ✅ HTTPS config written to traefik/dynamic/https.yml"
  echo ""
  echo "  📋 HTTPS routes configured:"
  echo "    • https://${ADHARA_DOMAIN}          → UI"
  echo "    • https://${ADHARA_DOMAIN}/api/*     → API"
  echo "    • https://registry.${ADHARA_DOMAIN}  → Docker Registry"
  echo ""
  echo "  📋 Next steps:"
  echo "    1. Add a DNS A record for registry.${ADHARA_DOMAIN} → your server IP"
  echo "    2. Restart Traefik to pick up the new config:"
  echo "         docker compose restart traefik"
  echo "    3. Verify certificate issued:"
  echo "         curl -v https://${ADHARA_DOMAIN}/ 2>&1 | grep 'SSL certificate'"
  echo ""
  echo "  🐳 Docker Registry (HTTPS):"
  echo "    After DNS propagates, push images using:"
  echo "         docker push registry.${ADHARA_DOMAIN}/my-app:latest"
  echo ""
  echo "  ⚠️  After HTTPS is working, update your OIDC provider:"
  echo ""
  echo "  For Logto (--profile auth):"
  echo "    1. Update OIDC_ISSUER in .env to use HTTPS domain"
  echo "    2. Update VITE_OIDC_ISSUER in ui/.env"
  echo "    3. Recreate: docker compose --profile auth up -d --build"
  echo ""
  echo "  For Zitadel (--profile zitadel):"
  echo "    1. Set ADHARA_HOST=${ADHARA_DOMAIN} in .env"
  echo "    2. Set ZITADEL_EXTERNALSECURE=true in docker-compose.yml"
  echo "    3. Recreate: docker compose --profile zitadel up -d --force-recreate"
  echo ""
fi

# ── Step 3: Docker daemon hardening ────────────────────────────────
echo "──────────────────────────────────────────────────────────────────"
echo "  Step 3: Docker Network Hardening"
echo "──────────────────────────────────────────────────────────────────"
echo ""

# Prevent Docker from bypassing UFW by adding iptables rules
DOCKER_UFW_CONF="/etc/ufw/after.rules"
MARKER="# ADHARA ENGINE — Block Docker port exposure"

if ! grep -q "$MARKER" "$DOCKER_UFW_CONF" 2>/dev/null; then
  echo "🔧 Adding iptables rules to prevent Docker from bypassing UFW..."
  cat >> "$DOCKER_UFW_CONF" <<'IPTEOF'

# ADHARA ENGINE — Block Docker port exposure
# Docker manipulates iptables directly, bypassing UFW.
# These rules ensure only allowed ports are reachable from outside.
*filter
:DOCKER-USER - [0:0]
# Allow established connections
-A DOCKER-USER -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN
# Allow internal Docker network traffic
-A DOCKER-USER -s 172.16.0.0/12 -j RETURN
-A DOCKER-USER -s 10.0.0.0/8 -j RETURN
-A DOCKER-USER -s 192.168.0.0/16 -j RETURN
# Allow localhost
-A DOCKER-USER -s 127.0.0.0/8 -j RETURN
# Allow public ports: HTTP, HTTPS (Zitadel is routed through Traefik)
-A DOCKER-USER -p tcp --dport 80 -j RETURN
-A DOCKER-USER -p tcp --dport 443 -j RETURN
# Block everything else to Docker containers
-A DOCKER-USER -j DROP
COMMIT
IPTEOF

  echo "  ✅ Docker iptables hardening added to ${DOCKER_UFW_CONF}"
  echo ""
  echo "  ⚠️  Restart UFW to apply: sudo ufw reload"
  ufw reload > /dev/null 2>&1
  echo "  ✅ UFW reloaded."
else
  echo "  ✅ Docker iptables rules already present — skipping."
fi

echo ""

# ── Summary ─────────────────────────────────────────────────────────
echo "══════════════════════════════════════════════════════════════════"
echo "  ✅ Security Hardening Complete"
echo "══════════════════════════════════════════════════════════════════"
echo ""
echo "  Public ports:"
echo "    22   — SSH"
echo "    80   — HTTP (→ HTTPS redirect if domain configured)"
echo "    443  — HTTPS"
echo "         (OIDC providers are routed through Traefik on 80/443)"
echo ""
echo "  Locked down (localhost only):"
echo "    5432  — PostgreSQL"
echo "    6379  — Redis"
echo "    5000  — Docker Registry"
echo "    8000  — API (direct)"
echo "    8080  — Traefik Dashboard"
echo "    9000  — MinIO API"
echo "    9001  — MinIO Console"
echo "    3001  — Logto OIDC"
echo "    3002  — Logto Admin"
echo "    3003  — Grafana"
echo "    3100  — Loki"
echo ""
if [ -n "$ADHARA_DOMAIN" ]; then
  echo "  🔒 HTTPS enabled for: ${ADHARA_DOMAIN}"
else
  echo "  ⚠️  HTTPS not configured — set ADHARA_DOMAIN in .env"
fi
echo ""
echo "  To access admin services remotely, use SSH tunneling:"
echo "    ssh -L 8080:localhost:8080 -L 3002:localhost:3002 -L 3003:localhost:3003 user@${ADHARA_HOST}"
echo ""
